#+title: Installing Python
#+setupfile: setup.org

* Installing Python with pre-bundled packages

There are several distributions that bundle Python with popular
scientific packages that are not included in the base install. This is a
good way to get everything set up and running with minimal hassle
(especially if your using Windows or Mac OS X).

A popular distribution is Continuum Analytics' Anaconda. To download
this, go [[https://store.continuum.io/cshop/products/][here]] and then select the Free version in the upper left panel.
Anaconda comes with a package manager, [[http://docs.continuum.io/conda/][conda]], that can be used to
install pre-built package, manage dependencies, set up virtual
environments, and switch between python versions. This [[http://continuum.io/blog/anaconda-python-3][post]] contains
information about using Python 3 with Anaconda.

* Base Python installation

Another option is to install the standard distribution of Python and
then just add extra packages as you need them. This is a very reasonable
way to operate on a GNU/Linux system, but this can be trickier to do on
a machine running Windows or Mac OS X, particularly if the extra
packages contain or depend on non-Python code. Below I outline how to
download Python and then install a non-standard package (IPython) with
pip. Python 3 is installed in the example, but Python 2 could be
installed in a similar manner.

** Installing on Mac OS X

*** Install homebrew

[[http://mxcl.github.io/homebrew/][homebrew]] is a package manager for Mac OS X. It is the easiest way to
install python, but it requires that you have Xcode installed. For
earlier versions of OS X, this should come with your install disk.
Otherwise, you can get it from the app store for free.

To install homebrew, copy this into a terminal and hit enter:

#+begin_example
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
#+end_example

After that, install python3 by running this in the terminal:

#+begin_example
  brew install python3
#+end_example

*** Install IPython

This is an enhanced interactive shell. To install it, open up command
prompt or terminal and run:

#+begin_example
  pip3 install ipython
#+end_example

Now you need to add the newly install ipython to your path. To do this,
open a terminal and enter:

#+begin_example
  echo 'export PATH=/usr/local/share/python3:$PATH' >> $HOME/.bash_profile
#+end_example

Once you have this, open a new terminal and type =ipython3= to enter
into the ipython shell.

** Installing on Windows

*** Download main python exe and run install

Download python 3: [[http://www.python.org/download]]

*** Add python to Path

Go here:

#+begin_example
  Control Panel > System and Security > System > Change settings >
  Advanced > Environmental Variables
#+end_example

Select =Path= variables and append:

#+begin_example
  ;C:\Python33;C:\Python33\Scripts;
#+end_example

You know this is working if you open up command prompt and type
"python".

*** Install distribute and pip

Download and install [[http://www.lfd.uci.edu/~gohlke/pythonlibs/#distribute][distribute]] and then [[http://www.lfd.uci.edu/~gohlke/pythonlibs/#pip][pip]].

These will allow you to install other python packages from the command
prompt.

*** Install IPython

This is an enhanced interactive shell. To install it, open up command
prompt or terminal and run:

#+begin_example
  pip install ipython
#+end_example

One you have this, type =ipython= in your terminal to enter into the
ipython shell.
