#+TITLE: Installing Python
#+SETUPFILE: setup.org


* Installing on Mac OS X

** Install homebrew

[[http://mxcl.github.io/homebrew/][homebrew]] is a package manager for Mac OS X. It is the easiest way to
install python, but it requires that you have Xcode installed. For
earlier versions of OS X, this should come with your install disk.
Otherwise, you can get it from the app store for free.

To install homebrew, copy this into a terminal and hit enter:

#+BEGIN_EXAMPLE
  ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
#+END_EXAMPLE

After that, install python3 by running this in the terminal:

#+BEGIN_EXAMPLE
  brew install python3
#+END_EXAMPLE

** Install IPython

This is an enhanced interactive shell. To install it, open up command
prompt or terminal and run:

#+BEGIN_EXAMPLE
  pip3 install ipython
#+END_EXAMPLE

Now you need to add the newly install ipython to your path. To do this,
open a terminal and enter:

#+BEGIN_EXAMPLE
  echo 'export PATH=/usr/local/share/python3:$PATH' >> $HOME/.bash_profile
#+END_EXAMPLE

Once you have this, open a new terminal and type =ipython3= to enter
into the ipython shell.

* Installing on Windows

** Download main python exe and run install

Download python 3: [[http://www.python.org/download]]

** Add python to Path

Go here:

#+BEGIN_EXAMPLE
  Control Panel > System and Security > System > Change settings >
  Advanced > Environmental Variables
#+END_EXAMPLE

Select =Path= variables and append:

#+BEGIN_EXAMPLE
  ;C:\Python33;C:\Python33\Scripts;
#+END_EXAMPLE

You know this is working if you open up command prompt and type
"python".

** Install distribute and pip

Download and install [[http://www.lfd.uci.edu/~gohlke/pythonlibs/#distribute][distribute]] and then [[http://www.lfd.uci.edu/~gohlke/pythonlibs/#pip][pip]].

These will allow you to install other python packages from the command
prompt.

** Install IPython

This is an enhanced interactive shell. To install it, open up command
prompt or terminal and run:

#+BEGIN_EXAMPLE
  pip install ipython
#+END_EXAMPLE

One you have this, type =ipython= in your terminal to enter into the
ipython shell.
