#+title: Installing Python with pre-bundled packages
#+setupfile: setup.org

There are several distributions that bundle Python with popular
scientific packages that are not included in the base install. This is
a good way to get everything set up and running with minimal hassle,
especially if you're using Windows or Mac OS X.

A popular distribution is Continuum Analytics' Anaconda. To download
this, go [[https://store.continuum.io/cshop/products/][here]] and then select the free version in the upper left
panel. Click the "I WANT PYTHON 3.4" link to use Python 3.4 as the
default Python version.

Anaconda comes with a package manager, [[http://docs.continuum.io/conda/][conda]], that can be used to
install pre-built package, manage dependencies, set up virtual
environments, and switch between Python versions.

If you would prefer not to download all the pre-bundled packages, you
can download [[http://conda.pydata.org/miniconda.html][miniconda]] instead. This gives you conda and the base
install of Python. You can then use conda to install particular
packages (and their dependencies) as you need them.
